#!/bin/bash

set -e

key=${1:-/sys/bus/nvmem/devices/rmem1/nvmem}

if ! [ -e $key ] ; then
  >&2 echo "Skipped populating root ssh key from eeprom as $key does not exist."
  exit 44
fi

l=256 # 2048-bit
n=$(od -An -N$l -vtx1 -w1 $key | tac | tr -d '\n ')
e=$(od -An -j$l -N8 -vtx8 --endian=little $key | tr -d '\n ' | sed ':a;s/^00//;ta')

mkdir -p -m 0755 /run/credstore/
ssh-keygen -i -m PKCS8 -f <(
  echo "-----BEGIN PUBLIC KEY-----"
  {
    printf "30 82 %04X 30 0D 06 09 2A 86 48 86 F7 0D 01 01 01 05 00 03 82 %04X 00 30 82 %04X 02 82 %04X 00 %s 02 %02X %s" \
      $(( $l + ${#e}/2 + 31 )) \
      $(( $l + ${#e}/2 + 12 )) \
      $(( $l + ${#e}/2 + 7 )) \
      $(( $l + 1 )) \
      ${n^^} \
      $(( ${#e}/2 )) \
      ${e^^}
  } | basenc --base16 -i -d | basenc --base64 -w64
  echo "-----END PUBLIC KEY-----"
) > /run/credstore/ssh.authorized_keys.root
chmod 0600 /run/credstore/ssh.authorized_keys.root
