#!/bin/sh

dir=$1
instances_file=$CREDENTIALS_DIRECTORY/instances.json
etc_hosts=/etc/hosts

[ -f $instances_file ] && [ -f $etc_hosts ] || exit 0

hostname=$([ -f /etc/hostname ] && cat /etc/hostname || /usr/bin/jq -jrs '.[0][.[1]|tostring]' $instances_file /proc/device-tree/serial-number)
! [ -z "$hostname" ] || exit 0
ip=$(grep -m1 $hostname $etc_hosts | cut -f1 -d' ')
! [ -z "$ip" ] || exit 0

mkdir -p /run/systemd/network
cat > /run/systemd/network/10-static.network <<INI
[Match]
Name=static
Type=vlan

[Network]
LinkLocalAddressing=no
Address=$ip/24
INI
