name: 'Build mkosi image'

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: systemd/mkosi@v17.1
      - name: Add arm64 support
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
#      - name: Generate secure boot key
#        run: mkosi --debug genkey
      - name: Show image summary
        run: mkosi summary
      - name: Build
        run: mkosi --debug --image-version=${{ github.ref_name }}
      - name: Compress Unified Kernel Image
        run: xz -k mkosi.output/system_*.efi
      - name: Calculate checksums
        run: >
          sha256sum
            mkosi.output/system_*.raw.xz
            mkosi.output/system_*.usr-*.raw.xz
            mkosi.output/system_*.efi.xz
          > SHA256SUMS
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            mkosi.output/system_*.raw.xz
            mkosi.output/system_*.usr-*.raw.xz
            mkosi.output/system_*.efi.xz
            SHA256SUMS
