name: 'Build mkosi image'

on:
  workflow_dispatch:
  push:
    branches:
      - main
permissions:
  contents: read
  pull-requests: read
jobs:
  build-image:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - uses: systemd/mkosi@v17.1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64
      - name: Install dependencies
        run: sudo apt-get install -y --no-install-recommends acpica-tools uuid-dev gcc-aarch64-linux-gnu gcc make patch build-essential git
      - name: Generate secure boot key
        run: mkosi --debug genkey
      - name: Show image summary
        run: mkosi summary
      - name: Build
        run: mkosi --debug
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: disk-image
          path: ubuntu-lunar.raw.xz
          retention-days: 1
