name: 'Build mkosi image'

on:
  workflow_dispatch:
  push:
    branches: ['main']
    tags: ['*']

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-26.04-arm
    steps:
      - uses: actions/checkout@v7
      - name: Install mkosi
        uses: systemd/mkosi@v26
      - name: Tolerate missing package changelogs
        run: |
          action_path=$(dirname "$(dirname "$(readlink -f /usr/bin/mkosi)")")
          python3 .github/workflows/patch-mkosi-changelog.py "$action_path/mkosi/manifest.py"
      - name: Install tools etc
        run: |
          sudo apt-get install -y --no-install-recommends jq uidmap systemd-container
      - name: Setup mkosi cache
        id: mkosi-cache
        uses: actions/cache/restore@v6
        with:
          path: mkosi.cache.tar.zst
          key: mkosi-${{ hashFiles('mkosi.conf') }}
      - name: Extract cache
        if: steps.mkosi-cache.outputs.cache-hit == 'true'
        run: sudo tar -xf mkosi.cache.tar.zst --use-compress-program zstdmt
      - name: Setup mkosi
        run: |
          touch mkosi.key mkosi.crt
          chmod 0600 mkosi.key mkosi.crt
          cat << EOF > mkosi.key
          ${{ secrets.MKOSI_KEY }}
          EOF
          cat << EOF > mkosi.crt
          ${{ secrets.MKOSI_CRT }}
          EOF
          echo -n ${{ github.ref_name }} > mkosi.version
          mkosi --json summary|jq -r '.Images[-1]|{OUTPUT_DIR:.OutputDirectory,OUTPUT:.Output,IMAGE_ID:.ImageId}|to_entries|map("\(.key)=\(.value)\n")|join("")' >> $GITHUB_ENV
      - name: Build images
        run: mkosi build
      - name: Setup Node.js
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/setup-node@v6
        with:
          node-version: 22
      - name: Generate changelog summary
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          .github/workflows/generate-changelog-summary.sh \
            ${{ env.OUTPUT_DIR }}/${{ env.OUTPUT }}.changelog.diff \
            cache/latest.changelog.xz \
            ${{ env.OUTPUT_DIR }}/${{ env.OUTPUT }}.changelog
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      - name: Test images
        run: sudo mkosi '--kernel-command-line-extra=systemd.run="echo hello"' vm
      - name: Compress outputs
        if: startsWith(github.ref, 'refs/tags/')
        run: xz -0 ${{ env.OUTPUT_DIR }}/${{ env.OUTPUT }}*.{raw,efi,changelog}
      - name: Generate SHA256SUMS
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ${{ env.OUTPUT_DIR }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          sha256sum ${{ env.OUTPUT }}*.{raw,efi,changelog}.xz >> SHA256SUMS
      - name: Append full changelog link
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          previous_tag=$(gh release list --repo ${{ github.repository }} --limit 1 --json tagName -q '.[0].tagName')
          if [ -n "$previous_tag" ] ; then
            echo -e "\n**Full Changelog**: https://github.com/${{ github.repository }}/compare/$previous_tag...${{ github.ref_name }}" >> ${{ env.OUTPUT_DIR }}/${{ env.OUTPUT }}.changelog.diff.md
          fi
      - name: Release
        uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          fail_on_unmatched_files: true
          generate_release_notes: false
          body_path: ${{ env.OUTPUT_DIR }}/${{ env.OUTPUT }}.changelog.diff.md
          files: |
            ${{ env.OUTPUT_DIR }}/${{ env.OUTPUT }}*.raw.xz
            ${{ env.OUTPUT_DIR }}/${{ env.OUTPUT }}*.efi.xz
            ${{ env.OUTPUT_DIR }}/${{ env.OUTPUT }}*.changelog.xz
            ${{ env.OUTPUT_DIR }}/${{ env.OUTPUT }}*.changelog.diff
            ${{ env.OUTPUT_DIR }}/${{ env.OUTPUT }}*.changelog.diff.md
            ${{ env.OUTPUT_DIR }}/SHA256SUMS
      - name: Build cache
        if: "!startsWith(github.ref, 'refs/tags/')"
        run: sudo tar -cf mkosi.cache.tar.zst mkosi.cache --use-compress-program zstdmt
      - name: Save cache
        if: "steps.mkosi-cache.outputs.cache-hit != 'true' && !startsWith(github.ref, 'refs/tags/')"
        uses: actions/cache/save@v6
        with:
          path: mkosi.cache.tar.zst
          key: mkosi-${{ hashFiles('mkosi.conf') }}
