name: 'Build mkosi image'

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744
      - run: |
          sudo apt-get install -y --no-install-recommends \
            python3 python3-pip python-is-python3 python3-pyelftools python3-pefile pipx \
            qemu-user-static binfmt-support bubblewrap dosfstools mtools uidmap debian-archive-keyring
      - run: |
          pipx ensurepath
          pipx install git+https://github.com/systemd/mkosi.git@v18
#      - name: Generate secure boot key
#        run: mkosi --debug genkey
      - name: Build (cached) tools
        run: mkosi --preset=tools
      - name: Show image summary
        run: mkosi summary
      - name: Build images
        run: mkosi --image-version=${{ github.ref_name }}
      - name: Rename SHA256SUMS
        run: mv mkosi.output/system_${{ github.ref_name }}.SHA256SUMS mkosi.output/SHA256SUMS
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          fail_on_unmatched_files: true
          generate_release_notes: true
          files: |
            mkosi.output/system_${{ github.ref_name }}.raw.xz
            mkosi.output/system_${{ github.ref_name }}.usr-*.raw.xz
            mkosi.output/system_${{ github.ref_name }}.efi
            mkosi.output/SHA256SUMS
